config/routes.rb
Rails.application.routes.draw do
  root 'rooms#top'
  get 'rooms/top'
  get 'rooms/search'
  resources :rooms
  resources :reservations

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

	validates :number_reservations, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}

  validate :date_check

  def date_check
    errors.add(:check_in, '日付が不正です') if check_in.nil? || check_in < Date.today
    errors.add(:check_out, '日付が不正です') if check_out.nil? || check_out < Date.today
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :restrict_with_error
  has_many :user_reservations, through: :reservations, source: :user

	validates :room_name, :introduction, :address, :room_image, presence: true
	validates :fee, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}

  mount_uploader :room_image, RoomImageUploader

  def self.search(search)
    if search
      Room.where(['room_name LIKE ?', "%#{search}%"]).or(Room.where(['address LIKE ?', "%#{search}%"]))
    else
      Room.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :restrict_with_error
  has_many :reservations, dependent: :restrict_with_error
  has_many :reserve_rooms, through: :reservations, source: :room

	validates :username, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :user_icon, UserIconUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def take_params
    {:id     => params[:id]}
  end

  helper_method :take_params
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :user_icon, :introduction])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :user_icon, :introduction])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %w[edit update destroy]

  def index
    @reservations = current_user.reservations
  end
  
  def new
    @room = Room.find_by(id: params[:id])
    @reservation = Reservation.new
  end
  
  def create
    @reservation = Reservation.new(
      reservation_params
      .merge(user_id: current_user.id)
      .merge(username: current_user.username)
      )
    if @reservation.save
      flash[:notice] = "部屋を予約しました"
      redirect_to("/reservations")
    else
      flash[:notice] = "予約に失敗しました"
      redirect_to("/reservations")
    end
  end
  
  def show
    @reservation = Reservation.where(id: params[:id])
  end
  
  def edit
    set_reservation
  end
  
  def update
    set_reservation
    if @reservation.update(
      reservation_params
      )
      flash[:notice] = "予約を変更しました"
      redirect_to("/reservations")
    else
      render "edit", status: :unprocessable_entity
    end
  end
  
  def destroy
    set_reservation
    @reservation.destroy
    flash[:notice] = "予約をキャンセルしました"
    redirect_to("/reservations")
  end

  private

  def set_reservation
    @reservation = Reservation.find_by(id: params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:number_reservations, :check_in, :check_out, :room_id, :room_name)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: %w[index top search]
  before_action :set_room, except: %w[index new create]

  def index
    @rooms = Room.search(params[:search])
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(
      room_params
      .merge(user_id: current_user.id)
      )
    if @room.save
      flash[:notice] = "部屋を追加しました"
      redirect_to("/rooms")
    else
      render "new", status: :unprocessable_entity
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @room.update(
      room_params
      )
      flash[:notice] = "部屋情報を編集しました"
      redirect_to("/rooms")
    else
      render "edit", status: :unprocessable_entity
    end
  end
  
  def destroy
    @room.destroy
    flash[:notice] = "部屋を削除しました"
    redirect_to("/rooms")
  end
  
  def top
  end
  
  def search
    @q = Room.ransack(params[:q])
    @rooms = @q.result
  end

  private

  def set_room
    @room = Room.find_by(id: params[:id])
  end

  def room_params
    params.require(:room).permit(:room_name, :introduction, :fee, :address, :room_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReserveApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <header>
      <div class="header-content">
        <h1><%= link_to "宿泊アプリ", "/", class: "nav-link" %></h1>
        <div class="search-outer">
          <%= form_tag("/rooms", method: :get) do %>
            <%= text_field_tag :search, "", {class: "input"} %>
            <%= submit_tag "検索" %>
          <% end %>
        </div>
      </div>
      <nav>
        <ul class="header-nav">
          <% if current_user.present? %>
            <%= link_to(edit_user_registration_path, class:"user-link") do %>
              <li class="user-info">
                <div>
                  <% if current_user.user_icon? %>
                    <%= image_tag current_user.user_icon.url, class:"user-icon" %>
                  <% else %>
                    <img src="/assets/default.png" class="user-icon" alt="ユーザーアイコン" %>
                  <% end %>
                </div>
                <p><%= current_user.username %>さん</p>
              </li>
            <% end %>
          <% end %>
          <li><%= link_to "ルーム一覧", rooms_path, class: "nav-content nav-link" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "ルーム登録", new_room_path, class: "nav-content nav-link" %></li>
            <li><%= link_to "予約一覧", reservations_path, class: "nav-content nav-link" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-content nav-link" %></li>
          <% else %>
            <li><%= link_to "ログイン", new_user_session_path, class: "nav-content nav-link" %></li>
            <li><%= link_to "新規登録", new_user_registration_path, class: "nav-content nav-link" %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <p class="form-error"><%= notice %></p>
    <p class="form-error"><%= alert %></p>

    <%= yield %>
    
  </body>
</html>

app/views/reservations/edit.html.erb
<h2>予約変更</h2>

  <div class="outer flex-col">
    <%= form_with model:@reservation do |f| %>
      <table class="reservation-new">
        <tr>
          <th><%= f.label :number_reservations ,"予約人数" %></th>
          <td><%= f.number_field :number_reservations, value:@reservation.number_reservations, class:"input" %> 人</td>
        </tr>
        <tr>
          <th><%= f.label :check_in ,"チェックイン" %></th>
          <td><%= f.date_field :check_in, default: @reservation.check_out, class:"input" %></td>
        </tr>
        <tr>
          <th><%= f.label :check_out ,"チェックアウト" %></th>
          <td><%= f.date_field :check_out, default: @reservation.check_out, class:"input" %></td>
        </tr>
      </table>
      <% @reservation.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>
      <div class="operation-box"><%= f.submit "予約" %></div>
    <% end %>
  </div>

app/views/reservations/index.html.erb
<h2>予約一覧</h2>

<div class="outer">
  <dl>
    <dt class="back-colored">予約ID</dt>
    <dd class="back-colored">ルーム名</dd>
    <% @reservations.each do |r| %>
      <dt><%= r.id %></dt>
      <dd>
        <%= link_to(reservation_path(r.id), class:"resevation-link link") do %>
          <%= r.room_name %>
        <% end %>
      </dd>
    <% end %>
</dl>
</div>

app/views/reservations/new.html.erb
<h2>予約ページ</h2>

<div class="resevation-container outer">
  <div class="room-info-box flex-col">
    <div>
      <h3><%= @room.room_name %></h3>
    </div>
    <div>
      <%= image_tag @room.room_image.url, class:"room-image" %>
    </div>
    <div>
      <table>
        <tr>
          <th>紹介</th>
          <td>
            <%= @room.introduction %>
          </td>
        </tr>
        <tr>
          <th>住所</th>
          <td>
            <%= @room.address %>
          </td>
        </tr>
        <tr>
          <th>料金</th>
          <td>
            <%= @room.fee %> 円
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="reservation-new-outer flex-col">
    <%= form_with model:@reservation, local: true do |f| %>
      <table class="reservation-new">
        <tr>
          <th><%= f.label :number_reservations ,"予約人数" %></th>
          <td><%= f.number_field :number_reservations, value:@reservation.number_reservations, class:"input" %> 人</td>
        </tr>
        <tr>
          <th><%= f.label :check_in ,"チェックイン" %></th>
          <td><%= f.date_field :check_in, default: @reservation.check_out, class:"input" %></td>
        </tr>
        <tr>
          <th><%= f.label :check_out ,"チェックアウト" %></th>
          <td><%= f.date_field :check_out, default: @reservation.check_out, class:"input" %></td>
        </tr>
      </table>
      <% @reservation.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <%= f.hidden_field :room_name, :value => @room.room_name %>
      <div class="operation-box"><%= f.submit "予約" %></div>
    <% end %>
  </div>
</div>

app/views/reservations/show.html.erb
<h2>予約詳細</h2>

<div class="room-container outer flex-col">
  <% @reservation.each do |r| %>
    <table>
      <tr>
        <th>ルーム名</th>
        <td><%= link_to(room_path(r.room_id), class:"resevation-link link") do %><%= r.room_name %><% end %></td>
      </tr>
      <tr>
        <th>チェックイン</th>
        <td><%= r.check_in.strftime("20%y年%m月%d日") %></td>
      </tr>
      <tr>
        <th>チェクアウト</th>
        <td><%= r.check_out.strftime("20%y年%m月%d日") %></td>
      </tr>
      <tr>
        <th>人数</th>
        <td><%= r.number_reservations %> 人</td>
      </tr>
    </table>
    <div class="operation-box">
      <%= link_to("予約変更", edit_reservation_path(r.id), class:"link") %>
      <%= link_to("予約キャンセル", reservation_path(r.id), data: { confirm: "本当にキャンセルしますか？" }, method: :delete, class:"link") %>
    </div>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<h2>ルーム情報変更フォーム</h2>

<div class="outer">
	<%= form_with model:@room do |r| %>
		<table>
			<tr>
				<th><%= r.label :room_name ,"ルーム名" %></th>
				<td><%= r.text_field :room_name, value:@room.room_name, class:"input" %></td>
			</tr>
			<tr>
				<th><%= r.label :introduction ,"紹介" %></th>
				<td><%= r.text_area :introduction, default: @room.introduction, class:"" %></td>
			</tr>
			<tr>
				<th><%= r.label :fee ,"料金" %></th>
				<td><%= r.number_field :fee, default: @room.fee, class:"input" %> 円</td>
			</tr>
			<tr>
				<th><%= r.label :address ,"住所" %></th>
				<td><%= r.text_field :address, value:@room.address, class:"input" %></td>
			</tr>
			<tr>
				<th><%= r.label :room_image ,"イメージ" %></th>
				<td><%= r.file_field :room_image, de:@room.room_image, class:"input" %></td>
			</tr>
		</table>
		<% @room.errors.full_messages.each do |message| %>
			<div class="form-error">
        <%= message %>
			</div>
    <% end %>
		<div class="operation-box"><%= r.submit "変更" %></div>
	<% end %>
</div>

app/views/rooms/index.html.erb
<h2>ルーム一覧</h2>

<div class="room-container outer">
  <% @rooms.each do |room| %>
    <div class="room-box flex-col">
      <%= link_to(room_path(room.id), class:"room-detail-link") do %>
        <div>
          <h3><%= room.room_name %></h3>
        </div>
        <div>
          <%= image_tag room.room_image.url, class:"room-image" %>
          <div>
            <p>　　　　住所：<%= room.address %></p>
            <p>　　　　料金：<%= room.fee %>円</p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h2>ルーム登録フォーム</h2>

<div class="outer">
	<%= form_with model:@room do |f| %>
		<table>
			<tr>
				<th><%= f.label :room_name ,"ルーム名" %></th>
				<td><%= f.text_field :room_name, class:"input" %></td>
			</tr>
			<tr>
				<th><%= f.label :introduction ,"紹介文" %></th>
				<td><%= f.text_area :introduction, class:"" %></td>
			</tr>
			<tr>
				<th><%= f.label :fee ,"料金" %></th>
				<td><%= f.number_field :fee, class:"input" %> 円</td>
			</tr>
			<tr>
				<th><%= f.label :address ,"住所" %></th>
				<td><%= f.text_field :address, class:"input" %></td>
			</tr>
			<tr>
				<th><%= f.label :room_image ,"ルームイメージ" %></th>
				<td><%= f.file_field :room_image, class:"input" %></td>
			</tr>
		</table>
		<% @room.errors.full_messages.each do |message| %>
			<div class="form-error">
        <%= message %>
			</div>
		<% end %>
		<div class="operation-box"><%= f.submit "ルーム登録" %></div>
	<% end %>
</div>

app/views/rooms/search.html.erb
<div class="room-container outer">
  <% @rooms.each do |room| %>
    <div class="room-box flex-col">
      <%= link_to(room_path(room.id), class:"room-detail-link") do %>
        <div>
          <h3><%= room.room_name %></h3>
        </div>
        <div>
          <%= image_tag room.room_image.url, class:"room-image" %>
          <div>
            <p>　　　　住所：<%= room.address %></p>
            <p>　　　　料金：<%= room.fee %>円</p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<h2>ルーム詳細</h2>

<div class="outer">
  <div class="image-box">
    <%= image_tag @room.room_image.url, class:"room-image" %>
  </div>
  <table>
    <tr>
      <th>ルーム名</th>
      <td class="show-table">
        <%= @room.room_name %>
      </td>
    </tr>
    <tr>
      <th>紹介</th>
      <td class="show-table">
        <%= @room.introduction %>
      </td>
    </tr>
    <tr>
      <th>料金</th>
      <td class="show-table">
        <%= @room.fee %>
      </td>
    </tr>
    <tr>
      <th>住所</th>
      <td class="show-table">
        <%= @room.address %>
      </td>
    </tr>
  </table>
  <div class="operation-box">
    <% if @room.user_id == current_user.id %>
      <%= link_to("編集", edit_room_path(@room.id), class:"link") %>
      <%= link_to("削除", room_path(@room.id), method: :delete, class:"link") %>
    <% else %>
      <%= link_to("この部屋を予約する", new_reservation_path(take_params), class:"link") %>
    <% end %>
  </div>
</div>

app/views/rooms/top.html.erb
<div class="outer">
  <div class="prefecture-box">
    <div class="area-link">
      <%= link_to controller: "rooms", action: "search", q: { address_cont: '北海道' } do %>
        <img src="/assets/hokkaido.jpeg" class="prefecture-img" alt="エリアイメージ" %>
        <p class="area-title">北海道</p>
      <% end %>
    </div>
    <div class="area-link">
      <%= link_to controller: "rooms", action: "search", q: { address_cont: '東京都' } do %>
      <img src="/assets/tokyo.jpeg" class="prefecture-img" alt="エリアイメージ" %>
      <p class="area-title">東京都</p>
      <% end %>
    </div>
    <div class="area-link">
      <%= link_to controller: "rooms", action: "search", q: { address_cont: '京都府' } do %>
      <img src="/assets/kyoto.jpeg" class="prefecture-img" alt="エリアイメージ" %>
      <p class="area-title">京都府</p>
      <% end %>
    </div>
    <div class="area-link">
      <%= link_to controller: "rooms", action: "search", q: { address_cont: '沖縄県' } do %>
      <img src="/assets/okinawa.jpeg" class="prefecture-img" alt="エリアイメージ" %>
      <p class="area-title">沖縄県</p>
      <% end %>
    </div>
  </div>
</div>